# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_app', '0002_auto_20170512_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_break',
            name='users',
            field=models.ManyToManyField(to='cbc_app.user'),
        ),
    ]
